# Generated by Django 2.2.6 on 2021-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210429_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='instagram_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
